### ISSUE TITLE
Score and other stuff

### ISSUE THREAD

**Issue by ravivarshney01** [VAR-solutions/Find-the-match#2]
Count score ,congratulate on winning & ask for play again.

**Comment by i-vishi** [comment]
i will go through it

**Comment by i-vishi** [comment]
added score card

**Comment by i-vishi** [comment]
added how to play modal

**Comment by ravivarshney01** [comment]
@i-vishi try to do something like this
https://codepen.io/anon/pen/RYOJjm

**Comment by i-vishi** [comment]
fix win modal alignment

**Comment by ravivarshney01** [comment]
I will try

**Comment by i-vishi** [comment]
alignment is fixed. check it out, and make necessoty changes @ravivarshney01 @antew-iiitv

**Comment by i-vishi** [comment]
made score board and congrats modal
