### ISSUE TITLE
developers option

### ISSUE THREAD

**Issue by i-vishi** [VAR-solutions/Find-the-match#3]
work on developers as suggested by @antew-iiitv . Reflect it as soon as possible, @antew-iiitv @ravivarshney01

**Comment by antew-iiitv** [comment]
Will look into the matter

**Comment by ravivarshney01** [comment]
@i-vishi @antew-iiitv  preview and close the issue

**Comment by antew-iiitv** [comment]
Necessary changes made.
and issue closed
